server:
  port: 8080

spring:
  application:
    name: college-server
  profiles:
    active: dev
  main:
    allow-circular-references: true

  # 设置mysql
  datasource:
    driver-class-name: ${college.datasource.driver-class-name}
    url: jdbc:mysql://${college.datasource.host}:${college.datasource.port}/${college.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${college.datasource.username}
    password: ${college.datasource.password}

  # 设置redis
  data:
    redis:
      host: ${college.data.redis.host}
      port: ${college.data.redis.port}
      password: ${college.data.redis.password}
      lettuce:
        pool:
          max-active: ${college.data.redis.lettuce.pool.max-active}
          max-idle: ${college.data.redis.lettuce.pool.max-idle}
          min-idle: ${college.data.redis.lettuce.pool.min-idle}
          time-between-eviction-runs: ${college.data.redis.lettuce.pool.time-between-eviction-runs}
  # 配置Spring Http请求的超时时间
  http:
    client:
      connect-timeout: 60s
      read-timeout: 120s

  # 配置SpringAI
  ai:
    # 豆包API
    openai:
      base-url: https://ark.cn-beijing.volces.com/api/v3
      api-key: ${DOUBAO_API_KEY}
      chat:
        completions-path: /chat/completions
        options:
          model: doubao-1-5-lite-32k-250115
          temperature: 0.3
    # 思考版本deepseek
    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-reasoner
          temperature: 0.7
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:sql/agent.sql

# 设置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: a311.college.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# 设置pageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true

# 设置阿里云OSS
college:
  aliyun:
    oss:
      endpoint: ${college.aliyun.oss.endpoint}
      bucket-name: ${college.aliyun.oss.bucket-name}

# 设置日志级别
logging:
  level:
    a311:
      college:
        server: info
        mapper: debug
        controller: info
    org.springframework.ai: debug # AI对话的日志级别
    com.itheima.ai: debug # 本项目的日志级别

# 设置knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体列表
  basic:
    enable: true
    username: root
    password: 123456




