server:
  port: 8080

spring:
  application:
    name: college-server
  profiles:
    active: dev
  main:
    allow-circular-references: true
  autoconfigure:
    exclude:
      # 由于在pom.xml文件中引入了spring-ai-starter-model-openai依赖，这个依赖会触发OpenAI的自动配置，包括（AudioSpeech，image）等项目中不用的，但是属于OpenAI会自动配置的Bean
      # ApiKey以前在spring.ai.openai.*中直接配置的，OpenAI的自动配置运行时能够找到这个ApiKey，能够完成一系列相关Bean的配置，即使很多Bean是用不到的，但是也是成功实例化了。
      # 现在由于要配置多个OpenAI兼容的模型，无法在spring.ai.openai.*中直接配置，而是改为手动配置，然后在实例化时从config中手动读取。但是spring的自动配置机制仍然会尝试实例化
      # OpenAI相关的一系列Bean，并且是从spring.ai.openai.*中读取的，所以说无法读取ApiKey和其他需要的配置，启动就会报错，所以说要在spring的autoconfigure中把不需要自动配置的Bean排除
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration
      # 同理，即使项目中不再使用DeepSeek模型，但是由于pom.xml中引入了spring-ai-deepseek依赖，所以说spring的autoconfigure机制会自动装配deepSeekChatModel的Bean，但是无法从
      # spring.ai.deepseek中读取到ApiKey等信息，所以说启动也会报错，所以说也需要在autoconfigure中排除不需要自动装配的DeepSeek相关的Bean
      # 或者更好的方式是：当确认了项目中不会再使用DeepSeek模型之后，就应该把相关依赖移除pom.xml文件
      - org.springframework.ai.model.deepseek.autoconfigure.DeepSeekChatAutoConfiguration

  # 设置mysql
  datasource:
    driver-class-name: ${college.datasource.driver-class-name}
    url: jdbc:mysql://${college.datasource.host}:${college.datasource.port}/${college.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${college.datasource.username}
    password: ${college.datasource.password}

  # 设置redis
  data:
    redis:
      host: ${college.data.redis.host}
      port: ${college.data.redis.port}
      password: ${college.data.redis.password}
      lettuce:
        pool:
          max-active: ${college.data.redis.lettuce.pool.max-active}
          max-idle: ${college.data.redis.lettuce.pool.max-idle}
          min-idle: ${college.data.redis.lettuce.pool.min-idle}
          time-between-eviction-runs: ${college.data.redis.lettuce.pool.time-between-eviction-runs}
  # 配置Spring Http请求的超时时间
  http:
    client:
      connect-timeout: 60s
      read-timeout: 120s

  # 配置SpringAI
  ai:
    # 由于项目需要配置两个兼容openai的模型，无法在SpringAI中自动配置，于是进行手动配置
    #    # 豆包API
    #    openai:
    #      base-url: https://ark.cn-beijing.volces.com/api/v3
    #      api-key: ${DOUBAO_API_KEY}
    #      chat:
    #        completions-path: /chat/completions
    #        options:
    #          model: doubao-1-5-lite-32k-250115
    #          temperature: 0.3
    #    # 思考版本Deepseek
    #    # 由于DeepSeek不同时支持工具调用和深度思考，现在已经废弃
    #    deepseek:
    #      base-url: https://api.deepseek.com
    #      api-key: ${DEEPSEEK_API_KEY}
    #      chat:
    #        options:
    #          model: deepseek-reasoner
    #          temperature: 0.7
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${QWEN_API_KEY}
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:sql/agent.sql



# 设置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: a311.college.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

# 设置pageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true

# 设置阿里云OSS
college:
  aliyun:
    oss:
      endpoint: ${college.aliyun.oss.endpoint}
      bucket-name: ${college.aliyun.oss.bucket-name}
  # 由于需要配置两个OpenAI兼容的模型，无法直接使用SpringAI的OpenAi配置，所以说需要进行手动配置，然后在Config中手动加载
  ai:
    doubao:
      base-url: ${college.ai.doubao.base-url}
      api-key: ${college.ai.doubao.api-key}
      model: ${college.ai.doubao.model}
      temperature: ${college.ai.doubao.temperature}
    qwen:
      base-url: ${college.ai.qwen.base-url}
      api-key: ${college.ai.qwen.api-key}
      model: ${college.ai.qwen.model}
      temperature: ${college.ai.qwen.temperature}



# 设置日志级别
logging:
  level:
    a311:
      college:
        server: info
        mapper: debug
        controller: info
    org.springframework.ai: debug # AI对话的日志级别
    com.itheima.ai: debug # 本项目的日志级别

# 设置knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体列表
  basic:
    enable: true
    username: root
    password: 123456




